### ISSUE TITLE
Oculus Rift

### ISSUE THREAD

**Issue by Bockbiertje** [Hotrian/OpenVRTwitchChat#4]
Is this supposed to be working with Oculus Rift as well?
As soon as I start Oculus home it will close the OpenVRTwitchChat.

**Comment by Hotrian** [comment]
Sorry, I don't have an Oculus Rift to test with, but this should be working through SteamVR. I assume Oculus Home does not draw through the OpenVR APIs and probably closes SteamVR when you launch it :(

**Comment by Sharkweathertv** [comment]
I'm currently trying to get this to work with the rift. Oculus home is going to start up on its own and it is required to stay open for the rift the register, pain in the butt but not a roadblock. As soon as you open steamVR it overrides oculus home, then I can load OpenVRTritchChat and set up the chat the way I like (using the world overlay). I have tried to load 'subnautica' and 'keep talking and no one explodes' but the overlay does not transfer. I am not getting an error when doing it in this order but am unable to get it to show up. I can be a guinea pig as I want this to work badly. Thanks for the hard work!

**Comment by Hotrian** [comment]
Could you look in the Data folder for output_log.txt, post the contents to a [Gist](http://gist.github.com) and post the link here or PM it to me on reddit when you get a chance?

**Comment by Mert7** [comment]
Using oculus rift, the twitch chat shows up in steamVR using world overlay, but it does not show up in Elite Dangerous. [output_log.txt](https://gist.github.com/Mert7/b59f6fe8c0ec0304c20f472108ea9bba) Looks fine to me though. I noticed that if I enable the display Mirror it still shows SteamVR with the chat overlay in it. Elite Dangerous had it's own mirroring window and both will run at the same time.
  To be clear, SteamVR mirror will show only steamVR world while running Elite Dangerous and Elite Dangerous Mirror only shows Elite Dangerous. And the Open VR Twitch Chat only shows in the Steam VR mirror.

  Did I miss a step or is something missing?

**Comment by Hotrian** [comment]
If it shows up in the SteamVR mirror but not in the headset then I suspect the image sent to the headset is not sent from SteamVR. ED likely sends the image directly to the Rift, and is overriding the SteamVR display, unfortunately.

I dug up a comment [here on Reddit](https://www.reddit.com/r/SteamVR/comments/4jc1u1/steamvr_overlay_not_working_with_oculus_rift_some/d37jgzn) where someone reports this exact behaviour with SteamVR Overlays in general (in ED).

> I have the same issue in elite: dangerous. I hit the steam button on the steam controller and the overlay loads. I can see it on the spy window in the monitor. But it does not render in the CV1.

Suggesting even the default SteamVR Overlays cannot draw to the Rift. This likely isn't a bug with my Overlay implementation or user error, but instead this is likely just an incompatibility with that game in particular.

Can someone try running SteamVR games such as The Lab? I realize you can't do anything without the touch controllers (which I'm assuming, possibly incorrectly, that you don't have yet) but you should at least be able to see if the Overlays will draw to the Rift. I assume you are using the Oculus Home version of Elite Dangerous, which might be setup a little different?

**Comment by Mert7** [comment]
@Hotrian I don't even have the oculus home version of Elite Dangerous installed. I launch from steam via "Launch in VR" option.  
With the Rift I loaded the lab, and overlay shows up there, it's just Elite Dangerous that does not work I guess. Dreams rekt.

**Comment by Hotrian** [comment]
@Mert7 Thanks for the update and the confirmation, that's unfortunate that ED is somehow skipping the compositor even though it is running through SteamVR :(.

@Sharkweathertv @Bockbiertje Can we get another confirmation that the overlays work in The Lab (and potentially other SteamVR games)?

We can close this issue if we can confirm it's an incompatibility with ED (and some other games such as Project Cars and Subnautica) and SteamVR Overlays and not my program itself.

**Comment by Hotrian** [comment]
Also if anyone has a chance it would be great if you could compile a list of games that the SteamVR Overlays do/do not work in to benefit future users. You can report your findings in here and I'll add a table or list or something on the front page.

**Comment by losangelesgraff** [comment]
can some one help me to get this to work in high fidelity. its open source. please

**Comment by Hotrian** [comment]
> can some one help me to get this to work in high fidelity. its open source. please

The Steam version of High Fidelity may work for you using [this guide](https://steamcommunity.com/games/586210/announcements/detail/1280555122088744691) to trick it into running on SteamVR. This works because Oculus does not support Windows 7, and SteamVR does. If both APIs are available but you're running with compatibility for Windows 7, SteamVR takes priority instead of the Oculus SDK.

**Comment by UnleashedOrb** [comment]
Twitch Chat does not work for Pavlov VR

**Comment by Hotrian** [comment]
Did you follow [this guide](https://steamcommunity.com/games/586210/announcements/detail/1280555122088744691)? I know people have definitely used it in Pavlov with Oculus Rift and SteamVR compatible headsets such as Vive, Index, etc. 

This would be due to the behavior of the Oculus SDK, and not an issue with OVRTC. It's in the name, *OpenVR*TwitchChat - Oculus Rift does not use the OpenVR APIs unless it needs to, so you will not be able to use OVRTC or other OpenVR/SteamVR Overlays unless you force it to run on SteamVR.

**Comment by Hotrian** [comment]
I have flagged this as Non-Issue as it is not strictly an issue with OVRTC. This is the intended behaviour of the Oculus SDK. I am not saying this is not an issue for any Oculus users - I hope nobody takes it that way. I would fix this one if it were possible, but for now the best answer is to trick your headset to use SteamVR when you want to use OVRTC, for whatever games the Windows 7 trick works for.

**Comment by stuartrpearson** [comment]
Not sure if related but revive workaround to get overlays to open in Oculus ![image](https://user-images.githubusercontent.com/78349941/120115374-4a806a00-c17b-11eb-835e-5c144533f5ca.png)
